### PR TITLE
fix: compatible with vueuse 10.x

### PR DESCRIPTION
**Pull request by aliuq**
### Description 描述

vueuse 10.x has removed some of the tool functions. see the [discussion](https://github.com/vueuse/vueuse/discussions/2986)

I've used the official repository's method of using `typeof` judgement directly

### CODE REVIEW

**Comment by ModyQyW** [comment]
Sorry, I am late. 

Actually, we can not use `@vueuse/core@10` in `uni-app` because the `vue` library used by `uni-app` doesn't export `TransitionGroup` but `@vueuse/core@10` needs it.

image

It is a good idea to remove some tool functions imported from '@vueuse/core'. But we are using `typeof` too much. Could you please do some organizations? You can put these tool functions into `src/utils.ts` and use them after importing them. Thanks!

**Comment by aliuq** [comment]
I just added `isString` and `isFunction` to `src/utils.ts`.

Regarding the upgrade to `@vueuse/core@10`, the `TransitionGroup` is actually handled by `vue-demi` for exports, and in versions prior to vue 3, vue-demi provided the mock function

image

**Comment by ModyQyW** [comment]
> I just added `isString` and `isFunction` to `src/utils.ts`.

Thanks!

> Regarding the upgrade to `@vueuse/core@10`, the `TransitionGroup` is actually handled by `vue-demi` for exports, and in versions prior to vue 3, vue-demi provided the mock function

Thanks for pointing it out! I will double-check the compatibility with vueuse 10.

**Comment by ModyQyW** [comment]
> Regarding the upgrade to @vueuse/core@10, the TransitionGroup is actually handled by vue-demi for exports, and in versions prior to vue 3, vue-demi provided the mock function

`vue-demi` only provides the mock function for v2, including v2.7. Since we are targeting v3, we can not use `@vueuse/core@10` in `uni-app (vue3)`.

**Pull request merged**
